"""Add is_active to tasks

Revision ID: 342576ac4ea6
Revises: e89028b7265d
Create Date: 2025-12-17 00:14:04.172277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342576ac4ea6'
down_revision = 'e89028b7265d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_active')
    # ### end Alembic commands ###
