"""Add task_participants table for many-to-many relationship

Revision ID: 38996c90af72
Revises: f4504cff59bd
Create Date: 2025-12-17 09:49:24.365501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38996c90af72'
down_revision = 'f4504cff59bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_participants',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_participants')
    # ### end Alembic commands ###
