"""Add progress column to tasks

Revision ID: 6e04da1a8f33
Revises: 38996c90af72
Create Date: 2025-12-17 12:54:01.028183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e04da1a8f33'
down_revision = '38996c90af72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'progress')
    # ### end Alembic commands ###
