"""Remove user relationship from Label

Revision ID: f4504cff59bd
Revises: 723cb1b35b02
Create Date: 2025-12-17 02:08:03.526708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4504cff59bd'
down_revision = '723cb1b35b02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index('ix_labels_name')
        batch_op.create_index(batch_op.f('ix_labels_name'), ['name'], unique=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_labels_name'))
        batch_op.create_index('ix_labels_name', ['name'], unique=False)

    # ### end Alembic commands ###
